[theme]
# Solorize theme
# primaryColor = "#919e8b"
# backgroundColor = "rgba(254,248,239,1)"
# secondaryBackgroundColor =  "#ebd2b9"
# textColor = "#6e7074"

# Dracula theme
primaryColor="#bd93f9"
backgroundColor="#282a36"
secondaryBackgroundColor="#44475a"
textColor="#f8f8f2"

font = "sans serif"
